- name: Running playbook on remote host
  hosts: 18.209.175.141
  become_method: sudo
  gather_facts: yes
  connection: ssh
  become_user: ec2-user
  
  vars:
    ansible_ssh_private_key_file: "/home/ec2-user/EssentialKeyPair.pem"

  tasks:
   - name: Printing Something
     shell: echo "My Name is AWS Ansible Remote Host"
