- name: Running playbook on remote host
  hosts: 18.209.175.141
  become_method: sudo
  gather_facts: yes
  connection: ssh
  become_user: ec2-user

  tasks:
   - name: Printing Something
     shell: echo "My Name is AWS Ansible Remote Host"
