- name: Running playbook on local host
  hosts: localhost
  
  tasks:
    - name: Copying file into Jenkins workspace
      copy: src=/var/lib/jenkins/workspace/EssentialKeyPair.pem dest=/var/lib/jenkins/workspace/GitHub/ remote_src=True

- name: Running playbook on remote host
  hosts: 18.209.175.141
  become_method: sudo
  gather_facts: yes
  connection: ssh
  become_user: ec2-user
  
  vars:
    ansible_ssh_private_key_file: "EssentialKeyPair.pem"

  tasks:
   - name: Printing Something
     shell: echo "My Name is AWS Ansible Remote Host"
